"""add_aviation_domain_models

Revision ID: acc64e142279
Revises: e4f5a6b7c8d9
Create Date: 2026-05-01 22:15:10.183083

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'acc64e142279'
down_revision = 'e4f5a6b7c8d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fabricante', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horas_totales', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('horas_proximo_mantenimiento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('umbral_alerta_horas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeronaves_matricula'), 'aeronaves', ['matricula'], unique=True)
    op.create_table('habilitacion_tipos',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilitacion_tipos_nombre'), 'habilitacion_tipos', ['nombre'], unique=True)
    op.create_table('tipo_operaciones',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_operaciones_nombre'), 'tipo_operaciones', ['nombre'], unique=True)
    op.create_table('pilotos',
    sa.Column('licencia_tipo', sa.Enum('privado', 'comercial', 'transporte_linea_aerea', name='licenciatipoenum'), nullable=False),
    sa.Column('numero_licencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('psicofisico_vence', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_pilotos_numero_licencia'), 'pilotos', ['numero_licencia'], unique=True)
    op.create_table('tipo_operacion_habilitaciones',
    sa.Column('tipo_operacion_id', sa.Integer(), nullable=False),
    sa.Column('habilitacion_tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habilitacion_tipo_id'], ['habilitacion_tipos.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacion_id'], ['tipo_operaciones.id'], ),
    sa.PrimaryKeyConstraint('tipo_operacion_id', 'habilitacion_tipo_id')
    )
    op.create_table('piloto_habilitaciones',
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('habilitacion_tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habilitacion_tipo_id'], ['habilitacion_tipos.id'], ),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.PrimaryKeyConstraint('piloto_id', 'habilitacion_tipo_id')
    )
    op.create_table('planificaciones',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('programado', 'completado', 'cancelado', name='planificacionstatusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_operacion_id'], ['tipo_operaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_vuelo',
    sa.Column('horas_vuelo', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('combustible_litros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('aceite_litros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('novedades', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planificacion_id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('aeronave_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planificacion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_vuelo')
    op.drop_table('planificaciones')
    op.drop_table('piloto_habilitaciones')
    op.drop_table('tipo_operacion_habilitaciones')
    op.drop_index(op.f('ix_pilotos_numero_licencia'), table_name='pilotos')
    op.drop_table('pilotos')
    op.drop_index(op.f('ix_tipo_operaciones_nombre'), table_name='tipo_operaciones')
    op.drop_table('tipo_operaciones')
    op.drop_index(op.f('ix_habilitacion_tipos_nombre'), table_name='habilitacion_tipos')
    op.drop_table('habilitacion_tipos')
    op.drop_index(op.f('ix_aeronaves_matricula'), table_name='aeronaves')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
